### ISSUE TITLE
What types of files are supported by ForgetMeNot?

### ISSUE THREAD

**Issue by WPFilmmaker** [tema6120/ForgetMeNot#1] opened 2020-10-04 18:43 UTC
Hi,

First of all thank you for this app, it looks very well done (and with more functions than similar apps) and I love that it is opensource (it has a lovely name and logo too!).

I have one question, I installed it but when I click "+" to load a file it does not read a deck file in csv, I have. This prompted me to open this tickets, what are the file types supported by ForgetMeNot?

AnyMemo (another app like yours but with less features) supports several files, which I think it is great since there are many apps for memorizing and they all use different files, so you have decks in different formats.

AnyMemo supports:
Mnemosyne XML 1.0 and 2.0
SuperMemo PPC XML
SuperMemo 2008 XML
Tab TXT
CSV
QA Text

While I think some of those formats are proprietary, I think ForgetMeNot should definitively support text and csv as they are quite common.

I will be glad to test your app thoroughly as I plan on using it to learn a language, so once I know how to load a deck expect more feedbacks to come :)

**Comment by tema6120** [comment] 2020-10-04 22:20
Thank you very much for your feedback. I will consider support of your suggested formats. Presently my app takes .txt files that is decorated in a special way:

```
Q:
empty
A:
vuoto


Q:
foreign
A:
straniero


Q:
good
A:
buono
```
You can read helping article on how to load deck from file by clicking on '(?)' icon:
![GIF_20201005_011015](https://user-images.githubusercontent.com/34657415/95028417-cab40580-06a8-11eb-9402-9e3ff0526187.gif)

**Comment by WPFilmmaker** [comment] 2020-10-04 22:56
@tema6120 Thanks a lot for your reply!

The csv file looks like: https://www.cram.com/flashcards/export/833213

CRAM is a very popular site but they do not export to txt, I could copy/past and save as txt but from what I can see the format is different.

If I have a txt file with this format:  **и	and        – # 1** ForgetMeNot won't be able to recognize it right?

I find your format very intuitive, BUT I never saw it in other apps, and do not know if there are decks available in such format. Do you know a site where I can try such deck?

If there are not it means the user has to manually create each flashcard which is a big no since there are many decks available but in different formats.

I would also recommend to add a sample deck so that when user install the app they can immediately play with it and see how the apps work.

**Comment by tema6120** [comment] 2020-10-05 09:39
Well, that's actually quite a complex question. There are many flashcard app that support different kind of flashcards: as plain text, rich text, pictures, audios. Some of them allow to export/import to file with specific formats. As far as I no, there is no standard file type for flashcards. Take CSV for example. This format was designed to represent spreadsheet, but no flashcards. Well, we could use .csv with two columns: questions and answers, but this format has no single specification and there may be considerable differences among implementations (Microsoft Excel CSV format, RFC-4180, tab delimited format and others).

I understand that it leads to a problem of lack of premade decks in my app. I have my own attitude towards premade decks. I approve using premade decks to study basic vocabulary, topical vocabulary or cards that contain sentences to do one-time exercise for testing oneself. For these kinds of deck I plan to provide my own catalog. I disapprove  using premade decks for intensive language studies and that's why:

- They don't always have context of using.
- They may not be decorated the way you would like.
- There is no emotional background. I encourage the idea of learning words, phrases that you really face: from movies, books, videos you are interested in, music, web-pages. It really helps to memorize information much easier.

Creating decks can be a time-consuming process. But it is possible to accelerate much if to approach it correctly. I advise you to always keep an open tab in the browser with your favorite dictionary web-page (I like [lingvolive.com](https://www.lingvolive.com/)) and a text file with a design template such as [here](https://drive.google.com/file/d/1pfAZ6tCgNMwCfXnc-F7-Fi5f8_W5eDXT/view?usp=sharing) so you can quickly transfer information using copy/paste. I'm going to make video on this topic.

I totally agree with the idea of first deck for introduction and I will add this in the near future.

**Comment by WPFilmmaker** [comment] 2020-10-05 12:37
Thank you for your detailed answer!

I get what you mean by your approach about decks, I will continue using your app as it is quite cool, and will follow the development closely.

Thanks about the video and for supporting the idea of adding a sample deck shipped with the app.

I also hope to see your app soon in f-droid :D

**Comment by tema6120** [comment] 2021-02-22 14:22
Since v1.4 **CSV**, **TSV** or any other **Delimiter-separated values** are fully supported. As I mentioned earlier csv format is not strict and there are many varieties of it. To overcome this ambiguity, I provide the user with the opportunity to clarify the format settings. You can select the required format from the predefined ones:

![file import](https://user-images.githubusercontent.com/34657415/108719724-9a221a80-7528-11eb-8d74-2acc72e8cb4f.png)

Or create your own DSV format settings:

![dsv format](https://user-images.githubusercontent.com/34657415/108720581-a9559800-7529-11eb-8301-bf81039c1fe5.png)

Since at this point I have no plans to support other formats, I close this issue.

**Closed by tema6120** 2021-02-22 14:22 UTC

**Comment by WPFilmmaker** [comment] 2021-02-22 14:44
@tema6120 thanks! By default you still use your format
q:
a:
right?

**Comment by vast4343** [comment] 2021-02-23 19:36
Добрый вечер Артем. Как я и написал в отзыве на гугл плей:  сначала прочитав справку я думал, что нужно все фразы брать в кавычки. На самом деле не нужно, просто при импорте колоды, необходимо выбрать нужный формат, из предлагаемых программой. Сделал несколько файлов ксв: сохранял из ексель сразу как  ксв (разделитель автоматически ставиться точка с запятой), далее сохранял из ескель как .txt с разделителем Tab и потом как ксв - затем оба сохранил с кодировкой текста utf-8 без BOM. В третьем файле csv оставил кодировку Кирилица, и при импорте выбрал ее, и программа импортировала файл без ошибок. Единственное когда попытался импортировать файл на 450 фраз программа написала: "Слишком большой файл для редактирования" и затем при сохранении колоды: файл содержит 2550 ошибок. Потом еще раз посмотрел файл, а у меня после 450 строк далее шли Табы на каждой следующей пустой строке, всего в файле было 3000 строк. Когда убрал все ненужные Табы, все импортировалось в программу. Единственное чего не хватает: возможности переноса из одной папки в другую, счетчика слов при тестировании (сколько осталось до конца в папке), и ночного режима. Спасибо за программу, очень нравиться!
